version: '3.1'

services:

  main:
    image: michaellihs/jenkins
    ports:
      - 8081:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
